name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
        submodules: true
    - name: compile for C
      run: sh -c 'CC=clang sh app.c -v'
    - name: compile for C++
      run: sh -c 'CC=clang sh app.cpp -v'
