name: CI
on: [push]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
        submodules: true
    - name: compile for C
      run: sh app.c -v
    - name: compile for C++
      run: sh app.cpp -v
